server:
  port: 9000
spring:
  application:
    name: wavetop-eureka # ????????????????????eureka??????

eureka:
  client:
    service-url:
#      defaultZone: http://192.168.1.166:9000/eureka/
      defaultZone: http://localhost:9000/eureka/