server:
  port: 9998

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.108.82:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Aa123456.
  application:
    name:  service-provider # 将来作为服务的名称，注入到eureka的中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true # 默认为true，